# Generated by Django 3.2.6 on 2021-08-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=50)),
                ('Quality', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
            ],
        ),
    ]
