# Generated by Django 3.2.6 on 2021-08-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='profile_pictures/')),
                ('name', models.CharField(max_length=50)),
                ('adp', models.FloatField()),
                ('op', models.FloatField()),
            ],
        ),
    ]
