# Generated by Django 3.2.6 on 2021-08-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_cleaning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaning',
            name='title',
        ),
    ]
