# Generated by Django 3.2.6 on 2021-08-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_remove_cleaning_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaning',
            name='subdepartment',
            field=models.CharField(choices=[('CLEANING', 'CLAENING'), ('UTENSILS', 'UTENSILS'), ('PET FOOD', 'PET FOOD')], default='CLEANING', max_length=50),
        ),
    ]
