# Generated by Django 3.2.6 on 2021-09-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_cleaning_subdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='subdepartment',
            field=models.CharField(choices=[('household', (('CLEANING', 'CLAENING'), ('UTENSILS', 'UTENSILS'), ('PET FOOD', 'PET FOOD'))), ('popular brands', (('FOOD', 'FOOD'), ('VEG_FRUIT', 'VEG_FRUIT'), ('BEVERAGES', 'BEVERAGES')))], default='household', max_length=50),
        ),
    ]
