# Generated by Django 3.2.6 on 2021-09-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_addtocart_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='Product',
            field=models.ImageField(upload_to=''),
        ),
    ]
