# Generated by Django 3.2.6 on 2021-09-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_alter_addtocart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='Product',
            field=models.CharField(max_length=50),
        ),
    ]
